// Generated by scripts/extract-factory-boundaries.mjs from public/assets/factory.glb.
// Do not edit numeric bounds by hand; rerun the script after replacing factory.glb.
import type { MovementRect } from './movementArea';

export interface FactoryCollisionRect extends MovementRect {
  id: string;
  kind: 'floor' | 'wall' | 'column';
  name: string;
  nodeIndex: number;
  meshIndex: number;
  minY: number;
  maxY: number;
}

export const FACTORY_COLLISION_META = {
  "source": "public/assets/factory.glb",
  "generatedFrom": "Khronos glTF Blender I/O v5.1.20",
  "targetSpan": 46,
  "scale": 0.423,
  "offset": [
    6.984,
    1.479,
    -0.824
  ],
  "sourceSceneMin": [
    -39.668,
    -3.493,
    -52.371
  ],
  "sourceSceneMax": [
    6.679,
    8.4,
    56.264
  ],
  "floorCount": 1,
  "wallCount": 22,
  "columnCount": 24
} as const;

export const FACTORY_FLOOR_RECTS: FactoryCollisionRect[] = [
  {
    "id": "node-2",
    "kind": "floor",
    "name": "Floor Floor-Grnd-Susp_65Scr-80Ins-100Blk-75PC [336315]",
    "nodeIndex": 2,
    "meshIndex": 2,
    "minX": -2.119,
    "maxX": 9.733,
    "minZ": -22.945,
    "maxZ": 8.216,
    "minY": 0,
    "maxY": 0.199
  }
];

export const FACTORY_WALL_RECTS: FactoryCollisionRect[] = [
  {
    "id": "node-3",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [337062]",
    "nodeIndex": 3,
    "meshIndex": 3,
    "minX": 2.514,
    "maxX": 2.554,
    "minZ": -7.154,
    "maxZ": -4.571,
    "minY": 0.209,
    "maxY": 1.479
  },
  {
    "id": "node-4",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [324423]",
    "nodeIndex": 4,
    "meshIndex": 4,
    "minX": -1.999,
    "maxX": 9.772,
    "minZ": -20.119,
    "maxZ": -20.079,
    "minY": 0.209,
    "maxY": 5.033
  },
  {
    "id": "node-12",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [325357]",
    "nodeIndex": 12,
    "meshIndex": 9,
    "minX": -1.999,
    "maxX": 5.199,
    "minZ": 8.121,
    "maxZ": 8.161,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-13",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [323724]",
    "nodeIndex": 13,
    "meshIndex": 10,
    "minX": 6.258,
    "maxX": 6.298,
    "minZ": -16.223,
    "maxZ": -12.37,
    "minY": 0.209,
    "maxY": 2.538
  },
  {
    "id": "node-15",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [326360]",
    "nodeIndex": 15,
    "meshIndex": 11,
    "minX": 1.983,
    "maxX": 2.024,
    "minZ": -17.679,
    "maxZ": -13.36,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-19",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [324323]",
    "nodeIndex": 19,
    "meshIndex": 15,
    "minX": 9.772,
    "maxX": 9.813,
    "minZ": -20.119,
    "maxZ": -16.203,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-24",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [324188]",
    "nodeIndex": 24,
    "meshIndex": 18,
    "minX": 6.298,
    "maxX": 9.813,
    "minZ": -16.223,
    "maxZ": -16.183,
    "minY": 0.209,
    "maxY": 2.538
  },
  {
    "id": "node-28",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [325404]",
    "nodeIndex": 28,
    "meshIndex": 20,
    "minX": 5.159,
    "maxX": 5.199,
    "minZ": 2.616,
    "maxZ": 8.121,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-34",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [341508]",
    "nodeIndex": 34,
    "meshIndex": 24,
    "minX": 2.554,
    "maxX": 5.159,
    "minZ": 2.603,
    "maxZ": 2.719,
    "minY": 0.209,
    "maxY": 1.903
  },
  {
    "id": "node-37",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [328463]",
    "nodeIndex": 37,
    "meshIndex": 27,
    "minX": 2.514,
    "maxX": 2.554,
    "minZ": -4.571,
    "maxZ": 8.121,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-38",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [326629]",
    "nodeIndex": 38,
    "meshIndex": 28,
    "minX": 1.544,
    "maxX": 1.584,
    "minZ": -13.36,
    "maxZ": -10.839,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-39",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [324780]",
    "nodeIndex": 39,
    "meshIndex": 29,
    "minX": 1.602,
    "maxX": 1.642,
    "minZ": -23,
    "maxZ": -21.712,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-74",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [329792]",
    "nodeIndex": 74,
    "meshIndex": 40,
    "minX": 6.933,
    "maxX": 6.973,
    "minZ": -11.793,
    "maxZ": -7.3,
    "minY": 0.209,
    "maxY": 1.39
  },
  {
    "id": "node-77",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [349134]",
    "nodeIndex": 77,
    "meshIndex": 41,
    "minX": 5.199,
    "maxX": 9.772,
    "minZ": 2.616,
    "maxZ": 2.656,
    "minY": 0.209,
    "maxY": 5.003
  },
  {
    "id": "node-78",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [326736]",
    "nodeIndex": 78,
    "meshIndex": 42,
    "minX": -1.999,
    "maxX": 1.544,
    "minZ": -10.879,
    "maxZ": -10.839,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-79",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [326446]",
    "nodeIndex": 79,
    "meshIndex": 43,
    "minX": -1.999,
    "maxX": 1.983,
    "minZ": -13.4,
    "maxZ": -13.36,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-82",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [323584]",
    "nodeIndex": 82,
    "meshIndex": 44,
    "minX": 6.356,
    "maxX": 6.973,
    "minZ": -12.37,
    "maxZ": -11.753,
    "minY": 0.209,
    "maxY": 1.39
  },
  {
    "id": "node-96",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [325946]",
    "nodeIndex": 96,
    "meshIndex": 50,
    "minX": 9.772,
    "maxX": 9.813,
    "minZ": -16.203,
    "maxZ": 2.656,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-97",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [326246]",
    "nodeIndex": 97,
    "meshIndex": 51,
    "minX": -1.999,
    "maxX": 2.024,
    "minZ": -17.719,
    "maxZ": -17.679,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-102",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [325242]",
    "nodeIndex": 102,
    "meshIndex": 54,
    "minX": -2.039,
    "maxX": -1.999,
    "minZ": -23,
    "maxZ": 8.161,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-104",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [326892]",
    "nodeIndex": 104,
    "meshIndex": 55,
    "minX": 6.933,
    "maxX": 9.772,
    "minZ": -7.3,
    "maxZ": -7.26,
    "minY": 0.209,
    "maxY": 1.39
  },
  {
    "id": "node-107",
    "kind": "wall",
    "name": "Basic Wall Wall-Partn_12P-70MStd-12P [323627]",
    "nodeIndex": 107,
    "meshIndex": 58,
    "minX": 6.258,
    "maxX": 6.397,
    "minZ": -12.37,
    "maxZ": -12.33,
    "minY": 0.209,
    "maxY": 2.538
  }
];

export const FACTORY_COLUMN_RECTS: FactoryCollisionRect[] = [
  {
    "id": "node-0",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [336202]",
    "nodeIndex": 0,
    "meshIndex": 0,
    "minX": 2.554,
    "maxX": 2.639,
    "minZ": -7.162,
    "maxZ": -7.077,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-5",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [336198]",
    "nodeIndex": 5,
    "meshIndex": 0,
    "minX": 2.554,
    "maxX": 2.639,
    "minZ": -12.328,
    "maxZ": -12.243,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-6",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [336063]",
    "nodeIndex": 6,
    "meshIndex": 0,
    "minX": 9.684,
    "maxX": 9.769,
    "minZ": -1.996,
    "maxZ": -1.911,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-10",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [340858]",
    "nodeIndex": 10,
    "meshIndex": 0,
    "minX": -1.993,
    "maxX": -1.908,
    "minZ": -20.073,
    "maxZ": -19.989,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-14",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [336055]",
    "nodeIndex": 14,
    "meshIndex": 0,
    "minX": 9.684,
    "maxX": 9.769,
    "minZ": -7.162,
    "maxZ": -7.077,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-26",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [336196]",
    "nodeIndex": 26,
    "meshIndex": 0,
    "minX": 2.554,
    "maxX": 2.639,
    "minZ": -14.91,
    "maxZ": -14.826,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-27",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [336059]",
    "nodeIndex": 27,
    "meshIndex": 0,
    "minX": 9.684,
    "maxX": 9.769,
    "minZ": -4.579,
    "maxZ": -4.494,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-29",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [336200]",
    "nodeIndex": 29,
    "meshIndex": 0,
    "minX": 2.554,
    "maxX": 2.639,
    "minZ": -9.745,
    "maxZ": -9.66,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-30",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [336047]",
    "nodeIndex": 30,
    "meshIndex": 0,
    "minX": 9.684,
    "maxX": 9.769,
    "minZ": -12.328,
    "maxZ": -12.243,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-41",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [336194]",
    "nodeIndex": 41,
    "meshIndex": 0,
    "minX": 2.554,
    "maxX": 2.639,
    "minZ": -17.493,
    "maxZ": -17.409,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-42",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [336208]",
    "nodeIndex": 42,
    "meshIndex": 0,
    "minX": 2.554,
    "maxX": 2.639,
    "minZ": 0.587,
    "maxZ": 0.672,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-43",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [336192]",
    "nodeIndex": 43,
    "meshIndex": 0,
    "minX": 2.554,
    "maxX": 2.639,
    "minZ": -20.076,
    "maxZ": -19.992,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-44",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [336043]",
    "nodeIndex": 44,
    "meshIndex": 0,
    "minX": 9.684,
    "maxX": 9.769,
    "minZ": -14.91,
    "maxZ": -14.826,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-48",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [340493]",
    "nodeIndex": 48,
    "meshIndex": 33,
    "minX": 7.296,
    "maxX": 7.381,
    "minZ": -20.076,
    "maxZ": -19.992,
    "minY": 0.209,
    "maxY": 4.701
  },
  {
    "id": "node-50",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [336051]",
    "nodeIndex": 50,
    "meshIndex": 0,
    "minX": 9.684,
    "maxX": 9.769,
    "minZ": -9.745,
    "maxZ": -9.66,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-51",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [340439]",
    "nodeIndex": 51,
    "meshIndex": 35,
    "minX": 4.925,
    "maxX": 5.01,
    "minZ": -20.076,
    "maxZ": -19.992,
    "minY": 0.209,
    "maxY": 4.636
  },
  {
    "id": "node-75",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [340505]",
    "nodeIndex": 75,
    "meshIndex": 0,
    "minX": 0.28,
    "maxX": 0.365,
    "minZ": -20.076,
    "maxZ": -19.992,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-76",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [336204]",
    "nodeIndex": 76,
    "meshIndex": 0,
    "minX": 2.554,
    "maxX": 2.639,
    "minZ": -4.579,
    "maxZ": -4.494,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-80",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [342193]",
    "nodeIndex": 80,
    "meshIndex": 0,
    "minX": 2.554,
    "maxX": 2.639,
    "minZ": 5.753,
    "maxZ": 5.837,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-81",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [336206]",
    "nodeIndex": 81,
    "meshIndex": 0,
    "minX": 2.554,
    "maxX": 2.639,
    "minZ": -1.996,
    "maxZ": -1.911,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-84",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [335977]",
    "nodeIndex": 84,
    "meshIndex": 0,
    "minX": 9.684,
    "maxX": 9.769,
    "minZ": -17.493,
    "maxZ": -17.409,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-98",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [336067]",
    "nodeIndex": 98,
    "meshIndex": 0,
    "minX": 9.684,
    "maxX": 9.769,
    "minZ": 0.587,
    "maxZ": 0.672,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-101",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [342134]",
    "nodeIndex": 101,
    "meshIndex": 0,
    "minX": 2.554,
    "maxX": 2.639,
    "minZ": 3.17,
    "maxZ": 3.255,
    "minY": 0.209,
    "maxY": 4.104
  },
  {
    "id": "node-103",
    "kind": "column",
    "name": "热轧H型钢柱 HN400x200x8x13 [335963]",
    "nodeIndex": 103,
    "meshIndex": 0,
    "minX": 9.684,
    "maxX": 9.769,
    "minZ": -20.076,
    "maxZ": -19.992,
    "minY": 0.209,
    "maxY": 4.104
  }
];

export const FACTORY_OBSTACLE_RECTS: FactoryCollisionRect[] = [
  ...FACTORY_WALL_RECTS,
  ...FACTORY_COLUMN_RECTS,
];
